name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push auth-service
        uses: docker/build-push-action@v5
        with:
          context: ./services/auth-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/auth-service:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push rfp-analysis-service
        uses: docker/build-push-action@v5
        with:
          context: ./services/rfp-analysis-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/rfp-analysis-service:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push web-app
        uses: docker/build-push-action@v5
        with:
          context: ./packages/web-app
          file: ./packages/web-app/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/web-app:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to staging
        run: echo "Deploy to staging environment"
        # Add actual deployment steps here (e.g., SSH to server, update Kubernetes, etc.)